#
# ~/dotfiles/bashrc
#

. ~/dotfiles/shell-common

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


# from sensible https://github.com/mrzool/bash-sensible/blob/master/sensible.bash
## GENERAL OPTIONS ##

# Prevent file overwrite on stdout redirection
# Use `>|` to force redirection to an existing file
#set -o noclobber

# Update window size after every command
shopt -s checkwinsize

# Automatically trim long paths in the prompt (requires Bash 4.x)
PROMPT_DIRTRIM=2

# Turn on recursive globbing (enables ** to recurse all directories)
shopt -s globstar 2> /dev/null

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend

# from sensible https://github.com/mrzool/bash-sensible/blob/master/sensible.bash
## SANE HISTORY DEFAULTS ##

# Save multi-line commands as one command
shopt -s cmdhist

# Huge history. Doesn't appear to slow things down, so why not?
#HISTSIZE=500000
#HISTFILESIZE=100000

# Don't record some commands
#export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# Use this timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
HISTTIMEFORMAT='%F %T '


# from sensible https://github.com/mrzool/bash-sensible/blob/master/sensible.bash
## BETTER DIRECTORY NAVIGATION ##

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null
# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null


# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
# unlimited
HISTSIZE=-1
HISTFILESIZE=-1
#HISTTIMEFORMAT="%F %T [device]: "

# Record each line as it gets issued
export PROMPT_COMMAND='$PROMPT_COMMAND; history -a'


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

if ! shopt -oq posix; then
    if [ -f ~/.bash_completion ]; then
        . ~/.bash_completion
    fi
fi


# load git completion
# source /usr/share/bash-completion/completions/git
# use git completion for dotfiles
# eval "$(complete -p git) dotfiles"

function nonzero_return() {
    RETVAL=$?
    [ $RETVAL -ne 0 ] && echo "$RETVAL"
}

# source git __git_ps1
# if [ -r /usr/share/git/git-prompt.sh ]; then
#     source /usr/share/git/git-prompt.sh
# fi 

# PS1="\[\e[34;1m\]\u\[\e[m\]@\[\e[31;1m\]\h\[\e[m\]:\[\e[33;1m\]\W\[\e[m\]\`__git_ps1\` $\[\e[31m\]\`nonzero_return\`\[\e[m\] "


